In [1]:
import pandas as pd

In [2]:
def merge(path, fileName):
    trainName = '../models/__models__/{}_{}.csv'.format(path, fileName)
    testName = trainName.replace('train', 'test')
    train = pd.read_csv(trainName)
    test = pd.read_csv(testName)
    data = pd.concat([train, test])
    return data

In [3]:
data = pd.read_csv('../input/data.csv')

data_stacking = data[['Id', 'Score']].copy()
data_stacking.head()

c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (12,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

                                     Id  Score
0  201e8bf2-77a2-3a98-9fcf-4ce03914e712      5
1  f4d51947-eac4-3005-9d3c-2f32d6068a2d      4
2  74aa7ae4-03a4-394c-bee0-5702d3a3082a      4
3  099661c2-4360-3c49-a2fe-8c783764f7db      5
4  97ca672d-e558-3542-ba7b-ee719bba1bab      5

In [4]:
models = [100, 101, 102]
for model in models:
    data_stacking = pd.merge(data_stacking, merge('lgbm_train', model), on = 'Id', how = 'left')
data_stacking.head()

,Id,Score,lgbm_model100,lgbm_model101,lgbm_model200
0,201e8bf2-77a2-3a98-9fcf-4ce03914e712,5,4.100287,4.282026,4.155004
1,f4d51947-eac4-3005-9d3c-2f32d6068a2d,4,4.508073,4.493492,4.446383
2,74aa7ae4-03a4-394c-bee0-5702d3a3082a,4,4.693461,4.661598,4.744894
3,099661c2-4360-3c49-a2fe-8c783764f7db,5,4.657754,4.582254,4.616804
4,97ca672d-e558-3542-ba7b-ee719bba1bab,5,4.724437,4.724305,4.726782

In [5]:
models = [1, 2, 3, 4, 5]
for model in models:
    data_stacking = pd.merge(data_stacking, merge('train_lgbmc_lc_label', model), on = 'Id', how = 'left')
data_stacking.head()

,Id,Score,lgbm_model100,lgbm_model101,lgbm_model200,lc_label_1,lc_label_2,lc_label_3,lc_label_4,lc_label_5
0,201e8bf2-77a2-3a98-9fcf-4ce03914e712,5,4.100287,4.282026,4.155004,0.000199,0.007818,0.140270,0.162465,0.339045
1,f4d51947-eac4-3005-9d3c-2f32d6068a2d,4,4.508073,4.493492,4.446383,0.000016,0.000334,0.026691,0.213236,0.641323
2,74aa7ae4-03a4-394c-bee0-5702d3a3082a,4,4.693461,4.661598,4.744894,0.000197,0.001392,0.010220,0.069199,0.825612
3,099661c2-4360-3c49-a2fe-8c783764f7db,5,4.657754,4.582254,4.616804,0.000009,0.000974,0.026951,0.145565,0.841762
4,97ca672d-e558-3542-ba7b-ee719bba1bab,5,4.724437,4.724305,4.726782,0.000229,0.000177,0.017185,0.261229,0.917013

In [6]:
data_stacking = pd.merge(data_stacking, merge('train_clf_0_label_lc_label', 1), on = 'Id', how = 'left')
data_stacking.head()

,Id,Score,lgbm_model100,lgbm_model101,lgbm_model200,lc_label_1_x,lc_label_2,lc_label_3,lc_label_4,lc_label_5,lc_label_1_y
0,201e8bf2-77a2-3a98-9fcf-4ce03914e712,5,4.100287,4.282026,4.155004,0.000199,0.007818,0.140270,0.162465,0.339045,0.000
1,f4d51947-eac4-3005-9d3c-2f32d6068a2d,4,4.508073,4.493492,4.446383,0.000016,0.000334,0.026691,0.213236,0.641323,0.005
2,74aa7ae4-03a4-394c-bee0-5702d3a3082a,4,4.693461,4.661598,4.744894,0.000197,0.001392,0.010220,0.069199,0.825612,0.005
3,099661c2-4360-3c49-a2fe-8c783764f7db,5,4.657754,4.582254,4.616804,0.000009,0.000974,0.026951,0.145565,0.841762,0.000
4,97ca672d-e558-3542-ba7b-ee719bba1bab,5,4.724437,4.724305,4.726782,0.000229,0.000177,0.017185,0.261229,0.917013,0.000

In [7]:
models = [1, 2, 3, 4, 5]
clfs = [0, 1, 2, 3]
for clf in clfs:
    for model in models:
        data_stacking = pd.merge(data_stacking, merge('train_clf_{}_label_lc_label'.format(clf), model), on = 'Id', how = 'left')
data_stacking.head()

,Id,Score,lgbm_model100,lgbm_model101,lgbm_model200,lc_label_1_x,lc_label_2_x,lc_label_3_x,lc_label_4_x,lc_label_5_x,...,lc_label_1_x,lc_label_2_y,lc_label_3_y,lc_label_4_y,lc_label_5_y,lc_label_1_y,lc_label_2,lc_label_3,lc_label_4,lc_label_5
0,201e8bf2-77a2-3a98-9fcf-4ce03914e712,5,4.100287,4.282026,4.155004,0.000199,0.007818,0.140270,0.162465,0.339045,...,0.03,0.035000,0.220,0.385000,0.420,0.03,0.040,0.280,0.375000,0.3850
1,f4d51947-eac4-3005-9d3c-2f32d6068a2d,4,4.508073,4.493492,4.446383,0.000016,0.000334,0.026691,0.213236,0.641323,...,0.00,0.010000,0.125,0.342500,0.610,0.00,0.005,0.080,0.300000,0.5925
2,74aa7ae4-03a4-394c-bee0-5702d3a3082a,4,4.693461,4.661598,4.744894,0.000197,0.001392,0.010220,0.069199,0.825612,...,0.00,0.000417,0.050,0.270000,0.705,0.00,0.010,0.035,0.290000,0.6700
3,099661c2-4360-3c49-a2fe-8c783764f7db,5,4.657754,4.582254,4.616804,0.000009,0.000974,0.026951,0.145565,0.841762,...,0.00,0.010000,0.055,0.340000,0.635,0.00,0.000,0.090,0.310000,0.6700
4,97ca672d-e558-3542-ba7b-ee719bba1bab,5,4.724437,4.724305,4.726782,0.000229,0.000177,0.017185,0.261229,0.917013,...,0.00,0.000000,0.000,0.272727,0.900,0.00,0.000,0.000,0.272727,0.9000

In [8]:
data_stacking = pd.merge(data_stacking, merge('train_lstm_len', 10), on = 'Id', how = 'left')
data_stacking.head()

,Id,Score,lgbm_model100,lgbm_model101,lgbm_model200,lc_label_1_x,lc_label_2_x,lc_label_3_x,lc_label_4_x,lc_label_5_x,...,lc_label_2_y,lc_label_3_y,lc_label_4_y,lc_label_5_y,lc_label_1_y,lc_label_2,lc_label_3,lc_label_4,lc_label_5,lstm_len_10
0,201e8bf2-77a2-3a98-9fcf-4ce03914e712,5,4.100287,4.282026,4.155004,0.000199,0.007818,0.140270,0.162465,0.339045,...,0.035000,0.220,0.385000,0.420,0.03,0.040,0.280,0.375000,0.3850,4.543209
1,f4d51947-eac4-3005-9d3c-2f32d6068a2d,4,4.508073,4.493492,4.446383,0.000016,0.000334,0.026691,0.213236,0.641323,...,0.010000,0.125,0.342500,0.610,0.00,0.005,0.080,0.300000,0.5925,4.484506
2,74aa7ae4-03a4-394c-bee0-5702d3a3082a,4,4.693461,4.661598,4.744894,0.000197,0.001392,0.010220,0.069199,0.825612,...,0.000417,0.050,0.270000,0.705,0.00,0.010,0.035,0.290000,0.6700,4.768332
3,099661c2-4360-3c49-a2fe-8c783764f7db,5,4.657754,4.582254,4.616804,0.000009,0.000974,0.026951,0.145565,0.841762,...,0.010000,0.055,0.340000,0.635,0.00,0.000,0.090,0.310000,0.6700,4.689859
4,97ca672d-e558-3542-ba7b-ee719bba1bab,5,4.724437,4.724305,4.726782,0.000229,0.000177,0.017185,0.261229,0.917013,...,0.000000,0.000,0.272727,0.900,0.00,0.000,0.000,0.272727,0.9000,4.793519

In [9]:
# ridge
data_stacking = pd.merge(data_stacking, merge('train_ridge', 'doufu'), on = 'Id', how = 'left')

data_stacking = pd.merge(data_stacking, merge('train_ridge', '1'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_ridge', '2'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_ridge', '3'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_ridge', '4'), on = 'Id', how = 'left')

data_stacking = pd.merge(data_stacking, merge('train_lasso', '1'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lasso', '2'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lasso', '3'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lasso', '4'), on = 'Id', how = 'left')

data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '0'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '100'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '101'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '102'), on = 'Id', how = 'left')

data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '200'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '201'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '202'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '203'), on = 'Id', how = 'left')
data_stacking = pd.merge(data_stacking, merge('train_lgbmr_lr', '204'), on = 'Id', how = 'left')

data_stacking.head()

,Id,Score,lgbm_model100,lgbm_model101,lgbm_model200,lc_label_1_x,lc_label_2_x,lc_label_3_x,lc_label_4_x,lc_label_5_x,...,lasso_4,lr_0,lr_100,lr_101,lr_102,lr_200,lr_201,lr_202,lr_203,lr_204
0,201e8bf2-77a2-3a98-9fcf-4ce03914e712,5,4.100287,4.282026,4.155004,0.000199,0.007818,0.140270,0.162465,0.339045,...,4.469982,4.349962,4.183126,4.052836,4.361708,4.024419,3.932488,4.003169,4.194271,4.208861
1,f4d51947-eac4-3005-9d3c-2f32d6068a2d,4,4.508073,4.493492,4.446383,0.000016,0.000334,0.026691,0.213236,0.641323,...,4.470049,4.551131,4.474679,4.475404,4.526335,4.572529,4.489206,4.499510,4.520303,4.353224
2,74aa7ae4-03a4-394c-bee0-5702d3a3082a,4,4.693461,4.661598,4.744894,0.000197,0.001392,0.010220,0.069199,0.825612,...,4.470013,4.696915,4.731439,4.696283,4.685141,4.760099,4.591912,4.598646,4.574344,4.751028
3,099661c2-4360-3c49-a2fe-8c783764f7db,5,4.657754,4.582254,4.616804,0.000009,0.000974,0.026951,0.145565,0.841762,...,4.470013,4.748631,4.585642,4.743619,4.563270,4.773982,4.709451,4.737960,4.491863,4.626491
4,97ca672d-e558-3542-ba7b-ee719bba1bab,5,4.724437,4.724305,4.726782,0.000229,0.000177,0.017185,0.261229,0.917013,...,4.470049,4.724791,4.744340,4.718763,4.725440,4.736618,4.741028,4.749907,4.720958,4.724191

In [10]:
data_stacking.to_csv('../input/data_stacking.csv', index = False)